# Site settings
title: Kiavash Samadi
description: Kiavash Samadi's Personal Website
baseurl: ""
url: "https://www.kiavashsamadi.com"

# User settings
username: Kiavash Samadi
user_description: This website is a work in progress.
user_title: Computer Science Student at UBC
email: kiavash@alumni.ubc.ca
# twitter_username:
# github_username:

# Google-analytics
google_analytics:
  id: UA-140777530-1

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude: ['package.json', 'src' , 'node_modules']
